<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\CMDocumentRepository.Application\CMDocumentRepository.Application.csproj" />
    <ProjectReference Include="..\CMDocumentRepository.Infrastructure\CMDocumentRepository.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>CMDocumentRepository</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
